<h1>Activation Functions</h1>

<h2>Hard Tanh</h2>
<p>Hard Tanhs are useful if we want to set all values over a threshold to one value, and all values below a threshold to another. For example, everything above 10 is just given the value 10, and everything below 0 is just given the value of 0.</p>

<centering>
<img src='images/hardtanh.png' style='width:50%; left:50%'/>
</centering>

<h2>Sigmoid</h2>
<p>Sigmoid functions are sensitive in the intermediate region between under- and over- saturation.</p>

<img src='images/sigmoid.png' style ='width:50%; background-color:white'/>

In [22]:
import torch
import torch.nn as nn

In [23]:
t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c).unsqueeze(1) # <1>
t_u = torch.tensor(t_u).unsqueeze(1) # <1>

In [24]:
n_samples = t_u.shape[0] #Number of samples is equal to the length of the t_u tensor
n_val = int(0.2 * n_samples) #Number of data points which we want to reserve for validation

torch.manual_seed(500)

shuffled_indices = torch.randperm(n_samples)
train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices

(tensor([ 2,  4,  5,  1,  7, 10,  6,  3,  0]), tensor([8, 9]))

In [25]:
#Set aside for training
t_u_train = t_u[train_indices]
t_c_train = t_c[train_indices]

#Set aside for validation
t_u_val = t_u[val_indices]
t_c_val = t_c[val_indices]

In [26]:
t_un_train = 0.1 * t_u_train
t_un_val = 0.1 * t_u_val

In [27]:
linear_model = nn.Linear(1, 1)
linear_model(t_un_val)

tensor([[0.4052],
        [0.3075]], grad_fn=<AddmmBackward0>)

In [29]:
linear_model.weight, linear_model.bias

(Parameter containing:
 tensor([[-0.0814]], requires_grad=True),
 Parameter containing:
 tensor([0.7994], requires_grad=True))